version: 1.0.{build}

install:
  - cd frontend
  - npm install

build_script:
  - cd frontend
  - npm run build

artifacts:
  - path: frontend/dist
    name: dist

deploy:
  provider: GitHubPages
  auth_token:
    secure: ${env:GITHUB_TOKEN}
  repo: FilSado/helpdesk
  branch: gh-pages
  folder: frontend/dist
  message: 'Deploy from Appveyor build %APPVEYOR_BUILD_NUMBER%'
