image: Visual Studio 2022

version: 1.0.{build}

install:
  - cmd: cd frontend && npm install

build_script:
  - cmd: cd frontend && npm run build

artifacts:
  - path: frontend/dist
    name: dist

deploy_script:
  - ps: |
      git config --global user.email "evgenia.maksimovna00@gmail.com"
      git config --global user.name "Евгения"
      cd frontend
      npx gh-pages -d dist -r https://$env:GITHUB_TOKEN@github.com/FilSado/helpdesk.git
